// src/extension/popup/components/Button.vue
<template>
  <button
    :disabled="disabled"
    :class="[`button--${type}`]"
    class="p-3 border-none w-[100px] rounded text-[10px] uppercase font-bold cursor-pointer 
    transition-colors active:opacity-90"
  >
    <slot v-if="$slots.default" />

    <span v-else-if="title">
      {{ title }}
    </span>
  </button>
</template>

<script>
export default {
  props: {
    title: String,

    disabled: Boolean,

    type: {
      type: String,
      default: 'primary',
    },
  },
};
</script>

<style scoped>
.button--primary {
  @apply bg-yellow-medium text-black;
}

.button--primary:disabled {
  @apply bg-grey-darker cursor-default text-grey-medium;
}

.button--ghost {
  @apply bg-transparent w-auto p-0 text-white;
}
</style>

// src/popup/components/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react'

type ButtonProps = {
  title?: string
  type?: 'primary' | 'ghost'
  children?: ReactNode
} & Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'type'>

const typeClassName = {
  primary:
    'bg-yellow-medium text-black disabled:bg-grey-darker disabled:cursor-default disabled:text-grey-medium',
  ghost: 'bg-transparent w-auto p-0 text-white',
}

const Button = ({
  title,
  type = 'primary',
  disabled,
  className = '',
  children,
  ...props
}: ButtonProps) => {
  return (
    <button
      disabled={disabled}
      className={`p-3 border-none w-[100px] rounded text-[10px] uppercase font-bold cursor-pointer transition-colors active:opacity-90 ${typeClassName[type]} ${className}`}
      {...props}
    >
      {children ?? (title ? <span>{title}</span> : null)}
    </button>
  )
}

export default Button
